CREATE TABLE NODES(
  NODE_ID IDENTITY NOT NULL,
  NAME VARCHAR_IGNORECASE,
  PHONE VARCHAR_IGNORECASE,
  DATA_ID VARCHAR_IGNORECASE NOT NULL,
  TYPE VARCHAR_IGNORECASE,
  MAKE VARCHAR_IGNORECASE,
  MODEL VARCHAR_IGNORECASE,
  EDGES ARRAY,
  PRIMARY KEY (NODE_ID)
);
